// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatchJobResponse = { video_id: string, status: string, };

export type SystemStatus = { cpu_usage: number, memory_usage: bigint, active_jobs: number, uptime: bigint, };

export type VideoMetadataPayload = { title: string, description: string, privacy_status: string, license: string, embeddable: boolean, public_stats_viewable: boolean, made_for_kids: boolean, contains_synthetic_media: boolean, paid_product_placement: boolean, tags: Array<string>, category_id: string, sub_details: { [key in string]?: string }, thumbnail_url: string | null, thumbnail_data_b64: string | null, scheduled_start_time: string | null, scheduled_start_time_millis: bigint | null, scheduled_end_time: string | null, publish_at: string | null, recording_date: string | null, language: string | null, default_language: string | null, default_audio_language: string | null, latency_preference: string | null, enable_auto_start: boolean | null, enable_auto_stop: boolean | null, enable_dvr: boolean | null, enable_content_encryption: boolean | null, start_with_low_latency: boolean | null, record_from_start: boolean | null, enable_monitor_stream: boolean | null, broadcast_stream_delay_ms: number | null, projection: string | null, is_compressed: boolean | null, compressed_fields: Array<string>, };

export type YouTubeVideoDetails = { id: string, title: string, description: string, thumbnail_url: string | null, privacy_status: string, view_count: bigint | null, url: string, };
