// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatchJobResponse = { video_id: string, status: string, };

export type SystemStatus = { cpu_usage: number, memory_usage: bigint, active_jobs: number, uptime: bigint, };

export type VideoMetadataPayload = { title: string, description: string, privacy_status: string, license: string, embeddable: boolean, public_stats_viewable: boolean, made_for_kids: boolean, contains_synthetic_media: boolean, paid_product_placement: boolean, tags: Array<string>, category_id: string, sub_details: { [key in string]?: string }, thumbnail_url: string | null, thumbnail_data_b64: string | null, scheduled_start_time: string | null, scheduled_start_time_millis: bigint | null, publish_at: string | null, recording_date: string | null, language: string | null, is_compressed: boolean | null, };

export type YouTubeVideoDetails = { id: string, title: string, description: string, thumbnail_url: string | null, privacy_status: string, view_count: bigint | null, url: string, };
