import prompts from 'prompts';
import fs from 'fs';
import path from 'path';

async function run() {
  console.log('\n🚀 Welcome to the YouTube Upload Manager Bootstrap Wizard');
  console.log('This will help you set up your .env file with the necessary secrets.\n');

  const response = await prompts([
    {
      type: 'text',
      name: 'registryUrl',
      message: 'System Registry URL',
      initial: 'http://127.0.0.1:8080'
    },
    {
      type: 'text',
      name: 'registryAdmin',
      message: 'Registry Admin Email',
      initial: 'admin@yt-manager.com'
    },
    {
      type: 'password',
      name: 'registryPass',
      message: 'Registry Admin Password',
      initial: 'admin123456'
    },
    {
      type: 'text',
      name: 'tenantUrl',
      message: 'Local/Tenant PocketBase URL',
      initial: 'http://127.0.0.1:8090'
    },
    {
      type: 'text',
      name: 'tenantAdmin',
      message: 'Tenant Admin Email',
      initial: 'admin@yt-manager.com'
    },
    {
      type: 'password',
      name: 'tenantPass',
      message: 'Tenant Admin Password',
      initial: 'admin123456'
    },
    {
      type: 'confirm',
      name: 'dummyMode',
      message: 'Enable YouTube Dummy Mode (Simulation)?',
      initial: true
    }
  ]);

  if (!response.registryUrl) {
    console.log('\n👋 Setup cancelled.');
    return;
  }

  const envContent = `# Generated by Bootstrap Wizard on ${new Date().toISOString()}

# --- System Registry Configuration ---
PUBLIC_MAIN_POCKETBASE_URL=${response.registryUrl}
MAIN_PB_ADMIN_EMAIL=${response.registryAdmin}
MAIN_PB_ADMIN_PASSWORD=${response.registryPass}

# --- PocketBase Configuration ---
PUBLIC_POCKETBASE_URL=${response.tenantUrl}
PB_ADMIN_EMAIL=${response.tenantAdmin}
PB_ADMIN_PASSWORD=${response.tenantPass}

# --- Web/Edge Mode Configuration ---
PUBLIC_EDGE_BACKEND_URL=https://api.yt-manager.com

# --- YouTube API Configuration ---
YOUTUBE_CLIENT_ID=your_client_id_here
YOUTUBE_CLIENT_SECRET=your_client_secret_here
YOUTUBE_REDIRECT_URI=http://localhost:1420

# --- Features ---
YT_DUMMY_MODE=${response.dummyMode}
PUBLIC_YT_DUMMY_MODE=${response.dummyMode}
`;

  fs.writeFileSync(path.join(process.cwd(), '.env'), envContent);
  console.log('\n✅ .env file created successfully!');
  console.log('You can now run "just setup" and "just up" to start the application.\n');
}

run();
