import PocketBase from 'pocketbase';
import fs from 'fs';
import path from 'path';

const PB_URL = process.env.PUBLIC_POCKETBASE_URL || 'http://127.0.0.1:8090';
const PB_ADMIN_EMAIL = process.env.PB_ADMIN_EMAIL || 'admin@yt-manager.com';
const PB_ADMIN_PASSWORD = process.env.PB_ADMIN_PASSWORD || 'admin123456';

const pb = new PocketBase(PB_URL);

async function authenticate() {
  try {
    await pb.collection('_superusers').authWithPassword(PB_ADMIN_EMAIL, PB_ADMIN_PASSWORD);
  } catch (e: any) {
    if (e.status === 404) {
      // Manual fallback for newer SDK + older PB
      const res = await fetch(`${PB_URL}/api/admins/auth-with-password`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email: PB_ADMIN_EMAIL, password: PB_ADMIN_PASSWORD })
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.message || 'Legacy auth failed');
      pb.authStore.save(data.token, data.admin);
    } else {
      throw e;
    }
  }
}

function pbTypeToTs(type: string): string {
  switch (type) {
    case 'text': return 'string';
    case 'number': return 'number';
    case 'bool': return 'boolean';
    case 'date': return 'string';
    case 'select': return 'string';
    case 'json': return 'any';
    case 'relation': return 'string';
    case 'file': return 'string';
    default: return 'any';
  }
}

async function generate() {
  console.log(`📡 Fetching PocketBase collections from ${PB_URL}...`);
  await authenticate();
  
  const collections = await pb.collections.getFullList();
  
  let content = `// This file is auto-generated by scripts/generate-types.ts. Do not edit manually.\n\n`;
  
  for (const coll of collections) {
    if (coll.system) continue;
    
    const interfaceName = coll.name.charAt(0).toUpperCase() + coll.name.slice(1).replace(/_([a-z])/g, (_, g) => g.toUpperCase());
    
    content += `export interface ${interfaceName}Record {\n`;
    content += `  id: string;\n`;
    
    // @ts-ignore - access fields/schema depending on version
    const fields = coll.fields || coll.schema || [];
    for (const field of fields) {
      const tsType = pbTypeToTs(field.type);
      const isRequired = field.required ? '' : '?';
      content += `  ${field.name}${isRequired}: ${tsType};\n`;
    }
    
    content += `  created: string;\n`;
    content += `  updated: string;\n`;
    content += `}\n\n`;
  }
  
  const outputPath = path.resolve('src/bindings/pocketbase_types.ts');
  fs.writeFileSync(outputPath, content);
  console.log(`✅ Generated PocketBase types at ${outputPath}`);
}

generate().catch(console.error);
